### ISSUE TITLE
Built Error

### ISSUE THREAD

**Issue by eq7755** [ghost1372/MoalemYar#7]
There may be an error in building the master project as following:

Error	CS0246	The type or namespace name 'Ookii' could not be found (are you missing a using directive or an assembly reference?)	MoalemYar	C:\Users\12610\OneDrive\桌面\MoalemYar-add-license-1\MoalemYar\MainWindow.xaml.cs	14	Active

**Comment by ghost1372** [comment]
hi @eq7755  Make sure all nugget packages are installed.
Here are some ways to retrieve packages.
https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore
or just run this command in Package Manager Console

> Install-Package Ookii.Dialogs
